# Generated by Django 3.0.3 on 2020-04-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jog',
            name='weather',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
