# Generated by Django 3.0.3 on 2020-04-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200423_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jog',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
