# Generated by Django 3.0.3 on 2020-04-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200423_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jog',
            name='weather',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
